### ISSUE TITLE
This seems amazing! Some suggestions

### ISSUE THREAD

**Issue by ibrunotome** [Larawiz/Larawiz#1]
- Option to type return of relationship methods instead of doc block
- Option to make uuid as primary key with `id` name
- Option to create observers automatically and enable they on EventServiceProvider
- Option to create policies automatically and register they on AuthServiceProvider

**this is not a request, they are just suggestions to make the package more amazing yet**

**Comment by ibrunotome** [comment]
Fews seconds later I've seen that the observers is already implemented 😆, really nice.

**Comment by DarkGhostHunter** [comment]
Thanks for the suggestions. This package needs suggestions. Lot of suggestions.

1. I really don't know if adding it would help in something. I consider it more clean (visually), and personally, I leave it for interfaces or abstract classes. It could be enabled flag on the yml, though.
2. Does `uuid: id` doesn't work?
3. That would need some engineering since it would have to edit the EventServiceProvider itself. Cool idea.
4. There are plans to also scaffold the HTTP later in the next version. Everything HTTP will go there.

**Comment by DarkGhostHunter** [comment]
# Update

### Option to type return of relationship methods instead of doc block ❌

Not priority given that it adds nothing of value (unless you point something of value)

### Option to make uuid as primary key with id name ✅

Already implemented:

```yaml
models:
  User:
    uuid: id
```

### Option to create observers automatically and enable them on EventServiceProvider ❤

Can be done. It needs some engineering since it's not very straightforward to implement.

### Option to create policies automatically and register they on AuthServiceProvider ❌

HTTP layer is not priority right now.
